const Projet = [
  {
    id: 1,
    nom: "Ydays",
    année: "2022 - 2023",
    brief: "Site vitrine",
    description:
      "Le site vitrine permets de presenter toutes les figurines réaliser depuis la création du projet et jusqu'a sa fin. Son langage primaire permet a n'importe qui de faire des rajouts, des modifications voir meme des améliorations",
    url: "https://ydetailedfigures.ylab.fr/index.html",
    screenShot: ["./assets/projets_screenshot/ydays.png"],
  },
  {
    id: 2,
    nom: "Sortable",
    année: "2023",
    brief: "Trieur de héros en fonctions de parametres predefinies",
    description:
      "Ce tableau récupère une api, qui est un lien vers une base de donnée où sont stockés tous les heros. Le but de se projet est de pouvoir decouvrir et utiliser les api et les fitres pour classer et ranger un tableau",
    url: [""],
    screenShot: ["./assets/projets_screenshot/sortable.png"],
  },
  {
    id: 3,
    nom: "Boxxle",
    année: "2023",
    brief: "Jeu d'arcade",
    description:
      "Le boxxle est un jeu d'arcade où le but est de déplacer des boites pour les mettre au bon endroit et valider le niveau",
    url: [""],
    screenShot: ["/assets/projets_screenshot/boxxle.png"],
  },
  {
    id: 4,
    nom: "Hangman Classique",
    année: "2023",
    brief: " Jeu du pendu console",
    description:
      "Le jeu reprend le principe du pendu et peut etre joué dans la console de son terminal",
    url: [""],
    screenShot: ["./assets/projets_screenshot/hangman-classique.png"],
  },
  {
    id: 5,
    nom: "Hangman Web",
    année: "2023",
    brief: "Jeu du pendu web",
    description:
      "Le jeu reprend le principe du pendu et peut etre joué dans la console de son terminal",
    url: ["https://github.com/Doctorwho07/Hangman-web"],
    screenShot: ["./assets/projets_screenshot/hangman-web.png"],
  },
  {
    id: 6,
    nom: "Groupie tracker",
    année: "2023",
    brief: "Receuil et découverte d'artiste",
    description: "Le projet groupie tracker",
    url: [""],
    screenShot: ["./assets/projets_screenshot/groupie-tracker.png"],
  },
  {
    id: 7,
    nom: "Quad",
    année: "2022",
    brief: "Quad drawing",
    description: "Le raid du week-end",
    url: [""],
    screenShot: ["./assets/projets_screenshot/quad.png"],
  },
  {
    id: 8,
    nom: "Word-search-solver",
    année: "2023",
    brief: "Word search solver",
    description: "Le raid du week-end",
    url: [""],
    screenShot: ["./assets/projets_screenshot/word-search-solver.png"],
  },
  {
    id: 9,
    nom: "Calculatrice",
    année: "2023",
    brief: "Calculatrice",
    description: "Petit exercice calcul mental",
    url: ["https://github.com/JAVA-ROUCHES-ALEXIS/TP/tree/main/TP%201"],
    screenShot: ["./assets/projets_screenshot/sortable.png"],
  },
  {
    id: 10,
    nom: "Cookie Clicker",
    année: "2023",
    brief: "Clicker",
    description: "Petit jeu dde clicker",
    url: [""],
    screenShot: ["./assets/projets_screenshot/cookie.png"],
  },
];
