const Projet = [
  {
    id: 1,
    nom: "Volontaide",
    année: "2023-2024",
    brief: "Volontaide",
    description:
      "Application qui a pour but de mettre en relation des volontaires ou bénévoles avec des particuliers et des associations",
    url: [""],
    screenShot: ["./assets/projets_screenshot/vav.jpg"],
  },
  {
    id: 2,
    nom: "Troc-Mon-Toit",
    année: "2023-2024",
    brief:
      "A platform for housing rentals offering a variety of accommodations from apartments to igloos, with advanced filtering features and a secure reservation process.",
    description:
      "The Troc Mon Toit application aims to digitize the rental services of an agency, offering a diverse selection of accommodations with advanced search functionalities. Users can view available lodgings, filter by city, type of lodging, amenities, and services, and make secure reservations.",
    url: ["https://github.com/B2-Info-23-24/php-Doctorwho07"],
    screenShot: ["./assets/projets_screenshot/trocmontoit.png"],
  },
  {
    id: 3,
    nom: "TechnoTalk",
    année: "2023",
    brief: "Forum discussion informatique",
    description:
      "Application qui a pour but de mettre en relation des volontaires ou bénévoles avec des particuliers et des associations",
    url: ["https://github.com/CLASSEROOM-B1/forum-technotalk"],
    screenShot: ["./assets/projets_screenshot/vav.jpg"],
  },
  {
    id: 4,
    nom: "Swopy-fun",
    année: "2023",
    brief: "",
    description: "",
    url: [""],
    screenShot: ["./assets/projets_screenshot/vav.jpg"],
  },
  {
    id: 5,
    nom: "Hangman Web",
    année: "2023",
    brief: "Jeu du pendu web",
    description:
      "Le jeu reprend le principe du pendu et peut être joué dans la console de son terminal",
    url: ["https://github.com/Doctorwho07/Hangman-web"],
    screenShot: ["./assets/projets_screenshot/hangman-web.png"],
  },
  // {
  //   id: 6,
  //   nom: "DroneGotchi",
  //   année: "2023",
  //   brief: "Jeu du tamagotchi",
  //   description:
  //     "envenue dans l'univers captivant de DroneGotchi, où vous pouvez prendre soin de votre compagnon de vol, Dronix ! Ce repository contient deux projets passionnants : les tâches à accomplir pour garder Dronix heureux et en forme, ainsi que le développement d'une application mobile dédiée à l'expérience DroneGotchi.",
  //   url: ["https://github.com/JAVA-ROUCHES-ALEXIS/Final_Project"],
  //   screenShot: ["./assets/projets_screenshot/dronegotchi.png"],
  // },
  {
    id: 7,
    nom: "Word-search-solver",
    année: "2023",
    brief: "Word search solver",
    description: "Le raid du week-end",
    url: [""],
    screenShot: ["./assets/projets_screenshot/word-search-solver.png"],
  },
  {
    id: 8,
    nom: "Cookie Clicker",
    année: "2023",
    brief: "Clicker",
    description: "Petit jeu de clicker",
    url: [""],
    screenShot: ["./assets/projets_screenshot/cookie.png"],
  },
  {
    id: 9,
    nom: "Ydays",
    année: "2022 - 2023",
    brief: "Site vitrine",
    description:
      "Le site vitrine permet de présenter toutes les figurines réalisées depuis la création du projet et jusqu'à sa fin. Son langage primaire permet à n'importe qui de faire des rajouts, des modifications voire même des améliorations",
    url: "https://github.com/Gougouli69/YDetailedFigures",
    screenShot: ["./assets/projets_screenshot/ydays.png"],
  },
  {
    id: 10,
    nom: "Quad",
    année: "2022",
    brief: "Quad drawing",
    description: "Le raid du week-end",
    url: [""],
    screenShot: ["./assets/projets_screenshot/quad.png"],
  },
  {
    id: 11,
    nom: "Sortable",
    année: "2023",
    brief: "Trieur de héros en fonctions de paramètres prédéfinis",
    description:
      "Ce tableau récupère une API, qui est un lien vers une base de données où sont stockés tous les héros. Le but de ce projet est de pouvoir découvrir et utiliser les API et les filtres pour classer et ranger un tableau",
    url: [""],
    screenShot: ["./assets/projets_screenshot/sortable.png"],
  },
  {
    id: 12,
    nom: "Boxxle",
    année: "2023",
    brief: "Jeu d'arcade",
    description:
      "Le boxxle est un jeu d'arcade où le but est de déplacer des boîtes pour les mettre au bon endroit et valider le niveau",
    url: [""],
    screenShot: ["./assets/projets_screenshot/boxxle.png"],
  },
  {
    id: 13,
    nom: "Hangman Classique",
    année: "2023",
    brief: " Jeu du pendu console",
    description:
      "Le jeu reprend le principe du pendu et peut être joué dans la console de son terminal",
    url: [""],
    screenShot: ["./assets/projets_screenshot/hangman-classique.png"],
  },
  {
    id: 14,
    nom: "Groupie tracker",
    année: "2023",
    brief: "Recueil et découverte d'artiste",
    description: "Le projet groupie tracker",
    url: [""],
    screenShot: ["./assets/projets_screenshot/groupie-tracker.png"],
  },
];
